# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0'
prepare_react_native_project!

flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'LxMusicMobile' do
  pod 'LXPlatform', :path => './LXPlatform'
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'LxMusicMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Add public cryptographic fixtures to the test bundle, not the shipped app.
    installer.aggregate_targets.map(&:user_project).uniq.each do |project|
      target = project.targets.find { |t| t.name == 'LxMusicMobileTests' }
      if target
        path = 'LxMusicMobileTests/Fixtures/crypto-fixtures.json'
        ref = project.files.find { |f| f.path == path } || project.main_group.new_file(path)
        target.resources_build_phase.add_file_reference(ref, true)
        project.save
      end
    end
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
